version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: accounts_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: accounts
      MYSQL_USER: jabba
      MYSQL_PASSWORD: hutt
    ports:
      - "3306:3306"
    volumes:
      - /home/oleg/projects/python/mysql-data:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
