[GLOBAL]
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.experimental.python.typecheck.pyright",
  "pants.backend.experimental.python.lint.ruff.check",
  "pants.backend.experimental.python.lint.ruff.format",
  "pants.backend.codegen.protobuf.lint.buf",
  "pants.backend.codegen.protobuf.python",
  "pants.backend.docker", 
  "pants.backend.experimental.javascript",
]
colors = true
local_store_dir = ".pants.d/lmdb_store"
pants_version = "2.21.0"

pants_ignore = [
  "/data",
  "/.venv",
]

[python]
interpreter_constraints = ["CPython>=3.12,<3.13"]

[source]
root_patterns = [
  "/",
  "protobuf/gen_py",
  "protobuf/src",
]

[python-infer]
imports = true

[test]
attempts_default = 3
use_coverage = true
output = "all"
timeout_default = 60
timeout_maximum = 600
